#!/bin/bash

#####################
# Author: Hardik Kwatra
# Date: 26th-Oct-2023
#
# Version: v1.0
#
# This script will report the AWS resource usage
#####################


set -x


# AWS S3
# AWS EC2
# AWS Lambda
# AWS IAM Users

# list s3 buckets
echo "Print list of s3 buckets"
aws s3 ls

# list EC2 Insatance
echo "Print list of ec2 Instances"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'

# list lambda
echo "Print list of lambda functions"
aws lambda list-functions

# list IAM users
echo "Print list of IAM Users"
aws iam list-users
